version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "monthly"
    exclude-paths:
      - ".github/workflows/release.yml"
    commit-message:
      prefix: "ci"
