[package]
name = "bmm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }
csv = "1.3.1"
dirs = "6.0.0"
lazy_static = "1.5.0"
once_cell = "1.20.3"
ratatui = "0.29.0"
regex = "1.11.1"
select = "0.6.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
sqlx = { version = "0.8.3", features = ["runtime-tokio", "sqlite"] }
tempfile = "3.16.0"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
url = { version= "2.5.4", features = ["serde"] }
which = "7.0.2"


[dev-dependencies]
pretty_assertions = "1.4.1"
