name: back-compat-pr

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  back-compat-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Build main
        run: cargo build --target-dir /var/tmp/main
      - name: Save bookmarks with bmm on main
        run: /var/tmp/main/debug/bmm save https://github.com/dhth/bmm
      - uses: actions/checkout@v4
      - name: Build head
        run: cargo build --target-dir /var/tmp/head
      - name: Run bmm on head
        run: /var/tmp/head/debug/bmm list -f json
