name: pr

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      deps: ${{ steps.filter.outputs.deps }}
      code: ${{ steps.filter.outputs.code }}
      rust: ${{ steps.filter.outputs.rust }}
      shell: ${{ steps.filter.outputs.shell }}
      workflows: ${{ steps.filter.outputs.workflows }}
      yml: ${{ steps.filter.outputs.yml }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            deps:
              - "Cargo.toml"
              - "Cargo.lock"
              - "deny.toml"
              - "mise.toml"
              - "mise.lock"
              - ".github/workflows/pr.yml"
            code:
              - ".sqlx/**"
              - "migrations/**"
              - "src/**"
              - "tests/**"
              - "**/*.rs"
              - Cargo.*
              - clippy.toml
              - dist-workspace.toml
              - rust-toolchain.toml
              - mise.toml
              - mise.lock
              - ".github/actions/**/*.yml"
              - ".github/workflows/pr.yml"
            rust:
              - "**/*.rs"
            shell:
              - "**.sh"
              - "mise.toml"
              - "mise.lock"
              - ".github/workflows/pr.yml"
            workflows:
              - ".github/**/*.yml"
              - "mise.toml"
              - "mise.lock"
            yml:
              - "**.yml"
              - "**.yaml"
              - "mise.toml"
              - "mise.lock"

  lint:
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    runs-on: ubuntu-latest
    env:
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@v6
      - name: Set up mise
        uses: jdx/mise-action@v4
        with:
          install_args: rust
      - name: Check formatting
        run: mise run fmt:check
      - name: Lint
        run: mise run lint

  build:
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@v6
      - name: Set up mise
        uses: jdx/mise-action@v4
        with:
          install_args: rust
      - name: Build
        run: mise run build

  test:
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      DATABASE_URL: sqlite://testdb/db.db
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up mise
        uses: jdx/mise-action@v4
        with:
          install_args: rust cargo:sqlx-cli
      - name: Run SQLx online checks
        run: mise run sqlx:online-checks
      - name: Run tests
        env:
          RUST_BACKTRACE: 0
        run: mise run test

  back-compat:
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
      - name: Set up mise for previous version
        uses: jdx/mise-action@v4
        with:
          install_args: rust
      - name: Build main
        run: cargo build --target-dir /var/tmp/main
      - name: Save bookmarks with bmm on main
        run: /var/tmp/main/debug/bmm save https://github.com/dhth/bmm
      - uses: actions/checkout@v6
      - name: Set up mise for new version
        uses: jdx/mise-action@v4
        with:
          install_args: rust
      - name: Build head
        run: cargo build --target-dir /var/tmp/head
      - name: Run bmm on head
        run: /var/tmp/head/debug/bmm list -f json

  lint-sh:
    needs: changes
    if: ${{ needs.changes.outputs.shell == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up mise
        uses: jdx/mise-action@v4
        with:
          install_args: shellcheck
      - name: Lint shell scripts
        run: mise run lint:shell

  lint-workflows:
    needs: changes
    if: ${{ needs.changes.outputs.workflows == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up mise
        uses: jdx/mise-action@v4
        with:
          install_args: actionlint
      - name: Lint workflows
        run: mise run lint:actions

  lint-yaml:
    needs: changes
    if: ${{ needs.changes.outputs.yml == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up mise
        uses: jdx/mise-action@v4
        with:
          install_args: yamlfmt
      - name: Lint YAML
        run: mise run lint:yaml

  dstlled-diff:
    needs: changes
    if: ${{ needs.changes.outputs.rust == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - id: get-dstlled-diff
        uses: dhth/dstlled-diff-action@0ab616345f8816e9046fdefec81b14ada815aaca # v0.2.0
        with:
          pattern: '**.rs'
          starting-commit: ${{ github.event.pull_request.base.sha }}
          ending-commit: ${{ github.event.pull_request.head.sha }}
          post-comment-on-pr: 'true'

  audit:
    needs: changes
    if: ${{ needs.changes.outputs.deps == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up mise
        uses: jdx/mise-action@v4
        with:
          install_args: rust aqua:EmbarkStudios/cargo-deny
      - name: Check dependencies and licenses
        run: mise run deny
